### ISSUE TITLE
airtable schema

### ISSUE THREAD

**Issue by gkarugi** [1024pix/pix-editor#81]
Bonjour! 

dans la documentation, nous avons ce qui suit : -

Si vous parvenez à vous authentifier, mais qu'une page blanche s'affiche, cela signifie très probablement que votre schéma de base Airtable est différent de celui utilisé pour le projet Pix

Où puis-je trouver le schéma ?

Merci d'avance!

**Comment by VincentHardouin** [comment]
Une réponse a été apporté : https://github.com/1024pix/pix/issues/5469
